# Generated by Django 5.0.7 on 2024-08-08 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_profile_direccion_profile_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clave',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='clave', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo_documento',
            field=models.IntegerField(choices=[(0, 'Cedula de Ciudadania'), (1, 'Cedula de Extranjeria'), (2, 'Permiso Especial de Permanencia'), (3, 'Pasaporte'), (4, 'Nit')], default=0),
        ),
    ]
