# Generated by Django 5.0.7 on 2024-08-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_remove_profile_clave_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
