# Generated by Django 5.0.7 on 2024-08-28 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_empresa_codigo_empresa_direccion_empresa_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_stock', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.medicamento')),
            ],
        ),
    ]
