# Generated by Django 5.0.7 on 2024-09-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_alter_customuser_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('emp', 'Empleado')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
