# Generated by Django 5.0.7 on 2024-09-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_customuser_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertas',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
