# Generated by Django 5.0.7 on 2024-09-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_alertas_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertas',
            name='cantidad',
        ),
    ]
