# Generated by Django 5.0.7 on 2024-10-08 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_remove_alertas_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='empresaid',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inventario.empresa'),
        ),
    ]
